services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - pg-docker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg-docker:5432/financeiroHome_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - dev-network

  pg-docker:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=financeiroHome_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      # Adicionando esta variável para criar o usuário postgres como superuser
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: postgres -c 'max_connections=50'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    networks:
      - dev-network
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@financeitohome.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - "5050:80"
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - pg-docker
    networks:
      - dev-network

volumes:
  postgres-data:

networks:
  dev-network:
    driver: bridge
