
POST http://localhost:8080/api/compras/1/compras
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJGaW5hbmNlaXJvSG9tZSIsInN1YiI6Imp1Y2EuYmFsYUBleGFtcGxlLmNvbSIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sImlhdCI6MTczODcxNDM3MywiZXhwIjoxNzM4ODAwNzczfQ.9ZdYRFxpkf7Rm8hK7Qyo4QgLm9ujdzRPEUgkkvHfaoI
Content-Type: application/json

{
  "categoria": "Eletrônicos",
  "dataCompra": "2024-02-04",
  "descricao": "Compra de notebook",
  "parcelas": 12,
  "valor": 5000,
  "status": "PENDENTE",
  "cartaoCredito": {
    "id": 1
  },
  "dataLimite": "2024-12-04T12:00:00",
  "valorTotal": 5000.00
}