POST http://localhost:8080/api/cartoes-credito
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJGaW5hbmNlaXJvSG9tZSIsInN1YiI6Imp1Y2EuYmFsYUBleGFtcGxlLmNvbSIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sImlhdCI6MTczNzI0NDgwNiwiZXhwIjoxNzM3MzMxMjA2fQ.2cmIxDV-iHDNJNzXIHneYBfTEUhVzZ-uYroLBBkpv7c
Content-Type: application/json

{
  "descricao": "Cartão Electron Master Blaster Turbo Gold",
  "limite": 2300000.00,
  "valor": 0.00,
  "limiteDisponivel": 2300000,
  "totalComprasAbertas": 0.00
}
