POST http://localhost:8080/status-parcelas
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJGaW5hbmNlaXJvSG9tZSIsInN1YiI6Im1hcmlvLmJhbGFAZXhhbXBsZS5jb20iLCJyb2xlcyI6W3siYXV0aG9yaXR5IjoiUk9MRV9VU0VSIn1dLCJpYXQiOjE3Mzg2ODUyMDIsImV4cCI6MTczODc3MTYwMn0.a1STobsbz13AbAsf5wmUjv9iFYksvn4uy7ov50vAD3U
Content-Type: application/json

{
           "parcelaId": 1,
           "status": "PENDENTE",
           "dataAlteracao": "2025-02-04T10:00:00",
           "usuarioId": 1
         }