POST http://localhost:8080/api/categorias
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJGaW5hbmNlaXJvSG9tZSIsInN1YiI6Imp1Y2EuYmFsYUBleGFtcGxlLmNvbSIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sImlhdCI6MTczOTIwNzAzNCwiZXhwIjoxNzM5MjkzNDM0fQ.ImGCggYkt0RG1d8QgRusVW5BpAtABpDrPWULtmkeYtA
content-Type: application/json

{
  "nome": "Alimentação",
  "tipo": "DESPESA"
}
