POST http://localhost:8080/api/cartao_credito
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJGaW5hbmNlaXJvSG9tZSIsInN1YiI6Imp1Y2EuYmFsYUBleGFtcGxlLmNvbSIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sImlhdCI6MTc0MDA4Nzc2MCwiZXhwIjoxNzQwMTc0MTYwfQ.g47REASwYS69EY9xSMv4JDtEfPfkIfEY9M-MNkhJcVE
content-Type: application/json

{
  "bandeiraCartao": "Mastercard",
  "numero": "5246312345678901",
  "limite": 10000.00,
  "limiteDisponivel": 8000.00,
  "totalComprasAbertas": 2000.00,
  "diaFechamento": 20,
  "diaVencimento": 28
}